### PR TITLE
Improvements (new options + requestAnimationFrame)

### PR DESCRIPTION
**Pull request by hahrens**

### CODE REVIEW

**Comment by hahrens** [comment]
i also added requestAnimationFrame instead of setInterval (when supported) and instance methods to pause/resume the animation. Sorry that this is all in the master branch, feel free to pick the changes by yourself and discard the PR.

ah, and you have to translate the readme changes to chinese :)

**Comment by mcc108** [comment]
👍 Thanks for your PR, I will review your contribution on the weekend.

**Comment by mcc108** [comment]
Thanks again for your contribution, it looks great now

**Comment by mcc108** [comment]
This feature has been released to [v2.2.0](https://www.npmjs.com/package/TagCloud)

**Pull request merged**
